title: Derek Coleman Associates Corporation Support Portal
description: Get help with your Microsoft Cloud Partner products and services from Derek Coleman Associates Corporation.
url: https://derek-coleman-associates-corporation.github.io
baseurl: /support-portal
theme: just-the-docs

markdown: kramdown
kramdown:
  auto_ids: false
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM

exclude:
  - vendor
  - Gemfile.lock
  - LICENSE

plugins:
  - jekyll-feed
  - jekyll-seo-tag

footer_links:
  - title: Support
    url: /support/
  - title: About Us
    url: /about/
  - title: Contact Us
    url: /contact/
